name: 'CI'
on:
  pull_request:
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-examples-changed:
    runs-on: ubuntu-latest
    outputs:
      example: ${{ steps.changes.outputs.examples }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            examples:
              - '.examples/**'

  check-compile:
    needs: check-examples-changed
    if: ${{ needs.changes.outputs.examples == 'true' }} || ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: Setup environment
        run: bash ./utils/scripts/setup-env.bash
      - name: Make environment variables persistent
        run: |
          source /opt/ros/*/setup.bash
          printenv >> "$GITHUB_ENV"
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "compile"
          no_compile_flag: false
          exclude_dirs: '["failing", "experiments"]'
  check-format:
    needs: check-examples-changed
    if: ${{ needs.changes.outputs.examples == 'true' }} || ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "format"
          exclude_dirs: '["failing", "experiments"]'
